// Package update installs newer AICE releases from GitHub and reports them at
// startup. It wraps github.com/creativeprojects/go-selfupdate so the release
// layout (aice_<os>_<arch> archives plus checksums.txt) is shared with the
// dependency installer.
package update

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/Masterminds/semver/v3"
	"github.com/creativeprojects/go-selfupdate"
)

const (
	// repositorySlug is the GitHub repository publishing AICE releases.
	repositorySlug = "ch1lam/aice-cli"

	// checksumsFileName matches the checksums.txt generated by the release
	// workflow; go-selfupdate validates each asset against it.
	checksumsFileName = "checksums.txt"

	// noCheckEnv disables the startup update notifier when set to a non-empty
	// value. Intended for CI and users who prefer to manage upgrades by hand.
	noCheckEnv = "AICE_NO_UPDATE_CHECK"

	// notifyInterval bounds how often the startup notifier contacts the API.
	notifyInterval = 24 * time.Hour

	// notifyTimeout bounds one startup check so a stalled connection cannot
	// delay the terminal session.
	notifyTimeout = 3 * time.Second
)

// Options controls one update operation. Zero values use process defaults,
// which keeps update testable with a fake updater and fake environment hooks.
type Options struct {
	Goos       string                 // default runtime.GOOS
	Goarch     string                 // default runtime.GOARCH
	Client     *selfupdate.Updater    // default GitHub updater with checksum validation
	Repository selfupdate.Repository  // default ParseSlug(repositorySlug)
	Current    string                 // installed version reported by the binary
	Getenv     func(string) string    // default os.Getenv
	Now        func() time.Time       // default time.Now
	Executable func() (string, error) // default selfupdate.ExecutablePath
	StatePath  string                 // notifier state file, default ~/.aice/update-state
	Stderr     io.Writer              // notifier output, default os.Stderr
	IsTerminal func() bool            // default: stdout and stderr are terminals
}

// CheckResult reports the newest release without installing it.
type CheckResult struct {
	Current   string
	Latest    string
	Available bool
}

// UpdateResult reports the outcome of an update.
type UpdateResult struct {
	Current string
	Latest  string
	Updated bool
}

// Check reports whether a newer release exists for the current platform.
func Check(ctx context.Context, opts Options) (CheckResult, error) {
	opts = normalize(opts)
	release, found, err := opts.Client.DetectLatest(ctx, opts.Repository)
	if err != nil {
		return CheckResult{}, fmt.Errorf("update: detect latest release: %w", err)
	}
	if !found {
		return CheckResult{}, errNoRelease(opts)
	}
	current := strings.TrimSpace(opts.Current)
	return CheckResult{
		Current:   current,
		Latest:    release.Version(),
		Available: versioned(current) && newer(release, current),
	}, nil
}

// Update installs the newest release over the running executable. force skips
// the version comparison so a build whose version cannot be compared (dev) or
// an already-current install can still be replaced.
func Update(ctx context.Context, opts Options, force bool) (UpdateResult, error) {
	opts = normalize(opts)
	exe, err := opts.Executable()
	if err != nil {
		return UpdateResult{}, fmt.Errorf("update: locate executable: %w", err)
	}
	if manager, ok := packageManagerInstall(exe); ok {
		return UpdateResult{}, fmt.Errorf(
			"update: aice is installed via %s; upgrade it with that package manager instead",
			manager,
		)
	}

	release, found, err := opts.Client.DetectLatest(ctx, opts.Repository)
	if err != nil {
		return UpdateResult{}, fmt.Errorf("update: detect latest release: %w", err)
	}
	if !found {
		return UpdateResult{}, errNoRelease(opts)
	}

	current := strings.TrimSpace(opts.Current)
	result := UpdateResult{Current: current, Latest: release.Version()}
	if !force {
		if !versioned(current) {
			return result, fmt.Errorf(
				"update: cannot compare version %q; run `aice update --force` to install the latest release",
				current,
			)
		}
		if !newer(release, current) {
			return result, nil
		}
	}
	if err := opts.Client.UpdateTo(ctx, release, exe); err != nil {
		if errors.Is(err, fs.ErrPermission) {
			return UpdateResult{}, fmt.Errorf(
				"update: cannot write %s; the install directory is not writable, so update aice through your package manager or reinstall it to a user directory: %w",
				exe,
				err,
			)
		}
		return UpdateResult{}, fmt.Errorf("update: replace executable: %w", err)
	}
	result.Updated = true
	return result, nil
}

// Notify prints an update hint to stderr when a newer release exists. It is
// best-effort: opt-out, terminal, and freshness gates mean it never fails or
// blocks a session, and a completed check is cached for notifyInterval so an
// up-to-date install does not contact the API on every launch.
func Notify(ctx context.Context, opts Options) {
	opts = normalize(opts)
	if opts.Getenv(noCheckEnv) != "" || !opts.IsTerminal() {
		return
	}
	if !dueForCheck(opts.StatePath, opts.Now) {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, notifyTimeout)
	defer cancel()
	release, found, err := opts.Client.DetectLatest(ctx, opts.Repository)
	if err != nil || !found || !versioned(opts.Current) {
		return
	}
	if err := markChecked(opts.StatePath, opts.Now); err != nil {
		return
	}
	if !newer(release, opts.Current) {
		return
	}
	fmt.Fprintf(
		opts.Stderr,
		"aice: update available: %s -> %s (run `aice update`)\n",
		strings.TrimSpace(opts.Current),
		release.Version(),
	)
}

func normalize(opts Options) Options {
	if opts.Goos == "" {
		opts.Goos = runtime.GOOS
	}
	if opts.Goarch == "" {
		opts.Goarch = runtime.GOARCH
	}
	if opts.Client == nil {
		opts.Client = defaultClient()
	}
	if opts.Repository == nil {
		opts.Repository = selfupdate.ParseSlug(repositorySlug)
	}
	if opts.Getenv == nil {
		opts.Getenv = os.Getenv
	}
	if opts.Now == nil {
		opts.Now = time.Now
	}
	if opts.Executable == nil {
		opts.Executable = selfupdate.ExecutablePath
	}
	if opts.StatePath == "" {
		if home, err := os.UserHomeDir(); err == nil {
			opts.StatePath = filepath.Join(home, ".aice", "update-state")
		}
	}
	if opts.Stderr == nil {
		opts.Stderr = os.Stderr
	}
	if opts.IsTerminal == nil {
		opts.IsTerminal = defaultIsTerminal
	}
	return opts
}

func defaultClient() *selfupdate.Updater {
	updater, err := selfupdate.NewUpdater(selfupdate.Config{
		Validator: &selfupdate.ChecksumValidator{UniqueFilename: checksumsFileName},
	})
	if err != nil {
		// NewUpdater only fails on invalid GitHub Enterprise URLs or filter
		// regexps; this static configuration can produce neither.
		panic(fmt.Sprintf("update: create updater: %v", err))
	}
	return updater
}

func defaultIsTerminal() bool {
	return isTerminal(os.Stdout) && isTerminal(os.Stderr)
}

func isTerminal(file *os.File) bool {
	info, err := file.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}

// packageManagerInstall reports whether the executable lives under a package
// manager's tree, where replacing the file would fight the manager.
func packageManagerInstall(path string) (string, bool) {
	lower := strings.ToLower(path)
	if strings.Contains(lower, "homebrew") || strings.Contains(lower, "/cellar/") {
		return "Homebrew", true
	}
	return "", false
}

func normalizeVersion(version string) string {
	return strings.TrimPrefix(strings.TrimSpace(version), "v")
}

// versioned reports whether version parses as a semantic version. Pre-release
// and build-metadata suffixes are accepted, but an invalid identifier (for
// example "1.2.3-01") is not.
func versioned(version string) bool {
	_, err := semver.NewVersion(normalizeVersion(version))
	return err == nil
}

// newer reports whether release is newer than current. It returns false when
// either side cannot be parsed, so a malformed current version degrades to
// "no update" instead of panicking.
func newer(release *selfupdate.Release, current string) bool {
	latest, err := semver.NewVersion(release.Version())
	if err != nil {
		return false
	}
	version, err := semver.NewVersion(normalizeVersion(current))
	if err != nil {
		return false
	}
	return latest.GreaterThan(version)
}

func errNoRelease(opts Options) error {
	return fmt.Errorf("update: no release asset for %s/%s", opts.Goos, opts.Goarch)
}

type stateFile struct {
	CheckedAt time.Time `json:"checked_at"`
}

func dueForCheck(path string, now func() time.Time) bool {
	content, err := os.ReadFile(path)
	if err != nil {
		return true
	}
	var state stateFile
	if err := json.Unmarshal(content, &state); err != nil {
		return true
	}
	return now().Sub(state.CheckedAt) >= notifyInterval
}

func markChecked(path string, now func() time.Time) error {
	if path == "" {
		return nil
	}
	content, err := json.Marshal(stateFile{CheckedAt: now()})
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, content, 0o600)
}
